// ── Deterministic, auto-derived codebase map ─────────────────────────────────
//
// `.vibestrate/CODEBASE.md` (human/prompt-facing) and `.vibestrate/codebase-map.json`
// (structured, server/UI-facing) are regenerated by `vibe learn`: a snapshot of
// stack, layout, entry points, best-effort HTTP routes, and tooling markers. Both
// are REGENERABLE CACHES, kept out of `VIBESTRATE.md` (authored project intent)
// the same way `.vibestrate/STATE.md` stays separate from it - see
// `src/core/project-state-digest.ts`. Everything here is deterministic (no model
// calls) so the map can be regenerated on demand without surprising drift.

import path from "node:path";
import { promises as fs } from "node:fs";
import { execa } from "execa";
import { detectFullProject } from "./project-detector.js";
import { listCodebaseFiles, searchCodebaseContent } from "../core/codebase-search-service.js";
import { writeTextAtomic, ensureDir, pathExists } from "../utils/fs.js";
import { redactSecretsInText } from "../core/diff-service.js";
import { vibestrateRoot } from "../utils/paths.js";

export type CodebaseMap = {
  schemaVersion: 1;
  generatedAt: string;
  /** git HEAD when generated; null when not a git repo. Drives staleness. */
  rev: string | null;
  project: {
    name: string;
    packageManager: string | null;
    type: string; // nextjs | vite | typescript | node | generic (detectProjectType)
    scripts: Record<string, string>;
    validationCommands: string[];
  };
  /** top-level dirs by tracked-file count, descending, capped at 20 */
  layout: Array<{ dir: string; files: number }>;
  /** file extensions by count, descending, capped at 10 */
  languages: Array<{ ext: string; files: number }>;
  /** paths that exist: package.json main/bin values + conventional entries, capped at 20 */
  entryPoints: string[];
  /** best-effort static route detection; honest about being heuristic */
  httpRoutes: {
    detected: Array<{ method: string; route: string; file: string }>;
    conventionFiles: string[]; // file-convention routes (app/**/route.ts, pages/api/**), capped at 50
    truncated: boolean;
  };
  /** detected tooling markers: vitest, eslint, prettier, docker, github-actions, ... */
  tooling: string[];
  totalTrackedFiles: number;
  /** any cap was hit or a source was unavailable */
  truncated: boolean;
  /** honest degradation notes, e.g. "not a git repository - layout and route scan skipped" */
  notes: string[];
};

export function codebaseMapMarkdownPath(projectRoot: string): string {
  return path.join(vibestrateRoot(projectRoot), "CODEBASE.md");
}

export function codebaseMapJsonPath(projectRoot: string): string {
  return path.join(vibestrateRoot(projectRoot), "codebase-map.json");
}

const MAX_LAYOUT_DIRS = 20;
const MAX_LANGUAGES = 10;
const MAX_ENTRY_POINTS = 20;
const MAX_HTTP_ROUTES = 100;
const MAX_CONVENTION_FILES = 50;
const MAX_SCRIPTS_RENDERED = 30;
const DEFAULT_PROMPT_MAX_BYTES = 4096;

const ENTRY_POINT_CANDIDATES = [
  "src/index.ts",
  "src/index.tsx",
  "src/main.ts",
  "src/cli/index.ts",
  "src/app.ts",
  "index.ts",
  "index.js",
  "app/layout.tsx",
  "src/App.tsx",
];

const HTTP_ROUTE_QUERY = "(app|router|server|api|fastify)\\.(get|post|put|patch|delete)\\(";
const HTTP_ROUTE_SNIPPET_RE = /\.(get|post|put|patch|delete)\(\s*["'`]([^"'`]+)/;

async function currentGitRev(projectRoot: string): Promise<string | null> {
  try {
    const r = await execa("git", ["rev-parse", "HEAD"], {
      cwd: projectRoot,
      reject: false,
    });
    if (r.exitCode !== 0) return null;
    return r.stdout.trim() || null;
  } catch {
    return null;
  }
}

function topLevelDir(p: string): string | null {
  const idx = p.indexOf("/");
  return idx === -1 ? null : p.slice(0, idx);
}

function fileExtension(p: string): string | null {
  const ext = path.extname(p);
  return ext ? ext.toLowerCase() : null;
}

/** Count occurrences of `keyOf(item)` (skipping null keys), sorted descending
 *  by count (ties broken alphabetically for determinism) and capped. */
function rankedCounts(
  items: string[],
  keyOf: (item: string) => string | null,
  cap: number,
): { entries: Array<{ key: string; count: number }>; capped: boolean } {
  const counts = new Map<string, number>();
  for (const item of items) {
    const key = keyOf(item);
    if (key === null) continue;
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  return {
    entries: sorted.slice(0, cap).map(([key, count]) => ({ key, count })),
    capped: sorted.length > cap,
  };
}

type EntryPointPackageFields = { main?: unknown; bin?: unknown };

async function readEntryPointFields(projectRoot: string): Promise<EntryPointPackageFields | null> {
  try {
    const raw = await fs.readFile(path.join(projectRoot, "package.json"), "utf8");
    return JSON.parse(raw) as EntryPointPackageFields;
  } catch {
    return null;
  }
}

function normalizeEntry(p: string): string {
  return p.replace(/^\.\//, "");
}

function declaredEntryPoints(pkg: EntryPointPackageFields | null): string[] {
  if (!pkg) return [];
  const out: string[] = [];
  const add = (v: unknown) => {
    if (typeof v === "string" && v.trim().length > 0) out.push(normalizeEntry(v.trim()));
  };
  add(pkg.main);
  if (typeof pkg.bin === "string") {
    add(pkg.bin);
  } else if (pkg.bin && typeof pkg.bin === "object") {
    for (const v of Object.values(pkg.bin as Record<string, unknown>)) add(v);
  }
  return out;
}

function isConventionRouteFile(p: string): boolean {
  const segments = p.split("/");
  const base = segments[segments.length - 1];
  if (segments[0] === "app" && (base === "route.ts" || base === "route.js")) return true;
  if (p.startsWith("pages/api/")) return true;
  if (p.startsWith("src/server/routes/") && segments.length === 4) return true;
  return false;
}

function detectTooling(paths: string[]): string[] {
  const tooling = new Set<string>();
  for (const p of paths) {
    const base = path.basename(p);
    if (/^vitest\.config\./.test(base)) tooling.add("vitest");
    if (/^jest\.config\./.test(base)) tooling.add("jest");
    if (/^\.eslintrc/.test(base) || /^eslint\.config\./.test(base)) tooling.add("eslint");
    if (/^\.prettierrc/.test(base) || /^prettier\.config\./.test(base)) tooling.add("prettier");
    if (base === "Dockerfile" || /^docker-compose/.test(base)) tooling.add("docker");
    if (p.startsWith(".github/workflows/")) tooling.add("github-actions");
    if (/^playwright\.config\./.test(base)) tooling.add("playwright");
  }
  return [...tooling].sort();
}

async function detectHttpRoutes(
  projectRoot: string,
): Promise<{ detected: CodebaseMap["httpRoutes"]["detected"]; truncated: boolean }> {
  const result = await searchCodebaseContent({
    projectRoot,
    query: HTTP_ROUTE_QUERY,
    regex: true,
  });
  const detected: CodebaseMap["httpRoutes"]["detected"] = [];
  let truncated = result.truncated;
  outer: for (const file of result.files) {
    for (const match of file.matches) {
      const m = HTTP_ROUTE_SNIPPET_RE.exec(match.text);
      if (!m) continue;
      if (detected.length >= MAX_HTTP_ROUTES) {
        truncated = true;
        break outer;
      }
      detected.push({ method: m[1]!.toUpperCase(), route: m[2]!, file: file.path });
    }
  }
  return { detected, truncated };
}

/**
 * Extract a fresh `CodebaseMap` by combining project detection, a single
 * tracked-file listing, and a single best-effort route content search. Every
 * source degrades honestly (empty arrays + a note) instead of throwing, so
 * this never fails a `vibe learn` run over a half-initialized project.
 */
export async function extractCodebaseMap(
  projectRoot: string,
  generatedAt: string,
): Promise<CodebaseMap> {
  const notes: string[] = [];
  let truncated = false;

  const detected = await detectFullProject(projectRoot);
  const rev = await currentGitRev(projectRoot);

  const fileList = await listCodebaseFiles({ projectRoot, max: 20000 });
  let trackedPaths: string[] = [];
  let layout: CodebaseMap["layout"] = [];
  let languages: CodebaseMap["languages"] = [];

  if (!fileList.available) {
    truncated = true;
    notes.push(
      detected.isGitRepo
        ? "codebase file listing unavailable - layout and route scan skipped"
        : "not a git repository - layout and route scan skipped",
    );
  } else {
    trackedPaths = fileList.paths;
    if (fileList.truncated) truncated = true;

    const layoutRanked = rankedCounts(trackedPaths, topLevelDir, MAX_LAYOUT_DIRS);
    layout = layoutRanked.entries.map(({ key, count }) => ({ dir: key, files: count }));
    if (layoutRanked.capped) truncated = true;

    const languageRanked = rankedCounts(trackedPaths, fileExtension, MAX_LANGUAGES);
    languages = languageRanked.entries.map(({ key, count }) => ({ ext: key, files: count }));
    if (languageRanked.capped) truncated = true;
  }

  const trackedSet = new Set(trackedPaths);
  const pkgFields = await readEntryPointFields(projectRoot);
  // package.json main/bin routinely point at gitignored build output (e.g.
  // `./dist/index.js`), so "exists" here means on disk, not tracked-by-git -
  // otherwise every compiled project would report zero declared entry points.
  const declaredCandidates = declaredEntryPoints(pkgFields);
  const declared: string[] = [];
  for (const candidate of declaredCandidates) {
    if (await pathExists(path.join(projectRoot, candidate))) declared.push(candidate);
  }
  const conventional = ENTRY_POINT_CANDIDATES.filter((c) => trackedSet.has(c));
  const combinedEntryPoints = [...new Set([...declared, ...conventional])];
  if (combinedEntryPoints.length > MAX_ENTRY_POINTS) truncated = true;
  const entryPoints = combinedEntryPoints.slice(0, MAX_ENTRY_POINTS);

  const { detected: detectedRoutes, truncated: routesTruncated } =
    await detectHttpRoutes(projectRoot);
  if (routesTruncated) truncated = true;
  const conventionMatches = trackedPaths.filter(isConventionRouteFile);
  if (conventionMatches.length > MAX_CONVENTION_FILES) truncated = true;
  const conventionFiles = conventionMatches.slice(0, MAX_CONVENTION_FILES);

  const tooling = detectTooling(trackedPaths);

  return {
    schemaVersion: 1,
    generatedAt,
    rev,
    project: {
      name: detected.name,
      packageManager: detected.packageManager === "unknown" ? null : detected.packageManager,
      type: detected.projectType,
      scripts: detected.packageScripts,
      validationCommands: detected.suggestedValidationCommands,
    },
    layout,
    languages,
    entryPoints,
    httpRoutes: {
      detected: detectedRoutes,
      conventionFiles,
      truncated: routesTruncated || conventionMatches.length > MAX_CONVENTION_FILES,
    },
    tooling,
    totalTrackedFiles: trackedPaths.length,
    truncated,
    notes,
  };
}

function renderStackSection(map: CodebaseMap): string[] {
  const lines = ["## Stack", "", `- Name: ${map.project.name}`, `- Type: ${map.project.type}`];
  lines.push(`- Package manager: ${map.project.packageManager ?? "unknown"}`);
  if (map.project.validationCommands.length > 0) {
    lines.push("- Validation commands:");
    for (const cmd of map.project.validationCommands) lines.push(`  - ${cmd}`);
  }
  lines.push("");
  return lines;
}

function renderCommandsSection(map: CodebaseMap): string[] {
  const entries = Object.entries(map.project.scripts).sort((a, b) => a[0].localeCompare(b[0]));
  if (entries.length === 0) return [];
  const lines = ["## Commands", ""];
  for (const [name, cmd] of entries.slice(0, MAX_SCRIPTS_RENDERED)) {
    lines.push(`- \`${name}\`: ${cmd}`);
  }
  lines.push("");
  return lines;
}

function renderLayoutSection(map: CodebaseMap): string[] {
  if (map.layout.length === 0) return [];
  const lines = ["## Layout", ""];
  for (const { dir, files } of map.layout) {
    lines.push(`- ${dir} - ${files} file${files === 1 ? "" : "s"}`);
  }
  lines.push("");
  return lines;
}

function renderLanguagesSection(map: CodebaseMap): string[] {
  if (map.languages.length === 0) return [];
  const lines = ["## Languages", ""];
  for (const { ext, files } of map.languages) {
    lines.push(`- ${ext} - ${files} file${files === 1 ? "" : "s"}`);
  }
  lines.push("");
  return lines;
}

function renderEntryPointsSection(map: CodebaseMap): string[] {
  if (map.entryPoints.length === 0) return [];
  return ["## Entry points", "", ...map.entryPoints.map((e) => `- ${e}`), ""];
}

function renderHttpRoutesSection(map: CodebaseMap): string[] {
  const { detected, conventionFiles, truncated } = map.httpRoutes;
  if (detected.length === 0 && conventionFiles.length === 0) return [];
  const lines = [
    "## HTTP routes (best effort)",
    "",
    "_Heuristic detection - verify against the code._",
    "",
  ];
  for (const r of detected) lines.push(`- ${r.method} ${r.route} (${r.file})`);
  if (conventionFiles.length > 0) {
    if (detected.length > 0) lines.push("");
    lines.push("Convention-based route files:");
    for (const f of conventionFiles) lines.push(`- ${f}`);
  }
  if (truncated) {
    lines.push("", "_more routes may exist - detection was capped._");
  }
  lines.push("");
  return lines;
}

function renderToolingSection(map: CodebaseMap): string[] {
  if (map.tooling.length === 0) return [];
  return ["## Tooling", "", ...map.tooling.map((t) => `- ${t}`), ""];
}

function renderNotesSection(map: CodebaseMap): string[] {
  if (map.notes.length === 0) return [];
  return ["## Notes", "", ...map.notes.map((n) => `- ${n}`), ""];
}

function renderSections(map: CodebaseMap): string {
  const blocks = [
    renderStackSection(map),
    renderCommandsSection(map),
    renderLayoutSection(map),
    renderLanguagesSection(map),
    renderEntryPointsSection(map),
    renderHttpRoutesSection(map),
    renderToolingSection(map),
    renderNotesSection(map),
  ].filter((block) => block.length > 0);
  return blocks.map((block) => block.join("\n")).join("\n");
}

/** Pure: the machine-owned `CODEBASE.md` body for a map. Mirrors the STATE.md
 *  self-describing header (`src/core/project-state-digest.ts`) so both
 *  machine-owned files read the same way. Same map => same body. */
export function renderCodebaseMap(map: CodebaseMap): string {
  const header = [
    "# Codebase map (auto-derived)",
    "",
    "> Machine-owned: regenerated by `vibe learn` (and on merge boundaries).",
    "> Do not hand-edit - changes are overwritten. Authored project intent,",
    "> conventions, and lessons live in `VIBESTRATE.md`.",
    "",
    `_Generated ${map.generatedAt}${map.rev ? ` at ${map.rev.slice(0, 12)}` : ""}._`,
    "",
  ].join("\n");
  return `${header}${renderSections(map)}\n`;
}

function truncateToBytes(text: string, maxBytes: number): string {
  if (Buffer.byteLength(text, "utf8") <= maxBytes) return text;
  const marker = "\n-- truncated --\n";
  const budget = Math.max(0, maxBytes - Buffer.byteLength(marker, "utf8"));
  const lines = text.split("\n");
  let out = "";
  for (const line of lines) {
    const candidate = out.length === 0 ? line : `${out}\n${line}`;
    if (Buffer.byteLength(candidate, "utf8") > budget) break;
    out = candidate;
  }
  return `${out}${marker}`;
}

/** Pure: bounded prompt-facing rendering (same sections, no machine-owned
 *  banner - the caller already knows this text was injected by the tool). */
export function renderCodebaseMapForPrompt(
  map: CodebaseMap,
  opts?: { maxBytes?: number; stale?: boolean },
): string {
  const maxBytes = opts?.maxBytes ?? DEFAULT_PROMPT_MAX_BYTES;
  const lines = ["# Codebase map (auto-derived)", ""];
  if (opts?.stale) {
    lines.push("(generated at an older commit - verify against the live repo)", "");
  }
  const full = `${lines.join("\n")}${renderSections(map)}`;
  return truncateToBytes(full, maxBytes);
}

/**
 * Regenerate both artifacts from the current repo state: extract -> render ->
 * redact -> write. Builds the full contents in memory first so a write is
 * always all-or-nothing per file (`writeTextAtomic` handles the atomic part).
 */
export async function writeCodebaseMap(
  projectRoot: string,
  generatedAt: string,
): Promise<{ map: CodebaseMap; markdownPath: string }> {
  const map = await extractCodebaseMap(projectRoot, generatedAt);
  const markdown = redactSecretsInText(renderCodebaseMap(map)).redacted;
  const json = redactSecretsInText(JSON.stringify(map, null, 2)).redacted;

  await ensureDir(vibestrateRoot(projectRoot));
  const markdownPath = codebaseMapMarkdownPath(projectRoot);
  await writeTextAtomic(markdownPath, markdown);
  await writeTextAtomic(codebaseMapJsonPath(projectRoot), json);

  return { map, markdownPath };
}

function isCodebaseMapShape(value: unknown): value is CodebaseMap {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as { schemaVersion?: unknown }).schemaVersion === 1
  );
}

/**
 * Load the persisted map. Missing file, unparsable JSON, or a schema-version
 * mismatch are all treated as "absent" rather than an error - regenerate-on-
 * demand beats carrying back-compat parsing for a regenerable cache.
 */
export async function loadCodebaseMap(
  projectRoot: string,
): Promise<{ present: boolean; map: CodebaseMap | null; stale: boolean }> {
  const absent = { present: false, map: null, stale: false } as const;
  let raw: string;
  try {
    raw = await fs.readFile(codebaseMapJsonPath(projectRoot), "utf8");
  } catch {
    return absent;
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return absent;
  }
  if (!isCodebaseMapShape(parsed)) return absent;

  const map = parsed;
  let stale = false;
  if (map.rev !== null) {
    const currentRev = await currentGitRev(projectRoot);
    stale = currentRev !== null && currentRev !== map.rev;
  }
  return { present: true, map, stale };
}
